remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ben's portfolio
description: [A short description of your site's purpose]

show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

github:
  zip_url: http://example.com/download.zip
  another_url: http://example.com/download2.zip
